# --- KONFIGURASI FINAL ---
TARGET_BODY_HEIGHT = 600
HEAD_OFFSET_Y = -205
HEAD_OFFSET_X = -2
HEAD_SCALE_FACTOR = 0.52
EXTRA_CANVAS_WIDTH = 400

# --- MOUTH DETECTION THRESHOLDS ---
MAR_THRESHOLD_100 = 0.50
MAR_THRESHOLD_75  = 0.35
MAR_THRESHOLD_50  = 0.20
MAR_THRESHOLD_25  = 0.05

# --- EYE DETECTION THRESHOLD ---
EAR_THRESHOLD_BLINK = 0.22

# --- BACKGROUND CONFIG ---
BACKGROUND_FILES = ["bg.jpg", "bg2.jpg", "bg3.jpg", "bg4.jpg"]

# --- BACKGROUND TRANSITION ANIMATION ---
TRANSITION_SPEED = 0.05  # Kecepatan transisi (semakin kecil = semakin lambat/halus)

# --- IDLE ANIMATION ---
BREATH_SPEED = 0.08
BREATH_AMPLITUDE = 3

# --- CANVAS CONFIG ---
DYNAMIC_TOP_MARGIN = 200
